In [17]:
import numpy as np
arr=np.array([[1,2,3],[2,5,7],[6,8,7]])
np.sum(arr,axis=1)
arr[0,1]

2

In [4]:
arr[0:2,0:2]#to acess a list of 2d with condition 

array([[1, 2],
       [2, 5]])

In [14]:
array3d=np.array([#to create and manipulate a 3d array
    [[1,2,3],[2,5,7],[6,8,7]]
    ,
    [[1,2,3],[2,5,7],[6,8,7]]

])
array3d[:,0:2,0:3]=0
print(array3d[:,:,:])

[[[0 0 0]
  [0 0 0]
  [6 8 7]]

 [[0 0 0]
  [0 0 0]
  [6 8 7]]]
