In [5]:
import numpy as np 
random_array=np.array([[1,2,3],[3,3,3],[4,7,8]])
print(random_array)
print(random_array.shape)


[[1 2 3]
 [3 3 3]
 [4 7 8]]
(3, 3)


In [13]:
float_array=np.array([1.1,2.2,3.3])
int_conv_array=float_array.astype(np.int32)
print(float_array)
print(int_conv_array)
float_array.dtype

[1.1 2.2 3.3]
[1 2 3]


dtype('float64')

In [17]:
array=np.array([2,3,4,5,6,7,8,9,0])
even_array=array[array%2==0]
print(even_array)

[2 4 6 8 0]


In [21]:
dummy_array=np.array([2,3,4,5,6,7,8,9,0])
reshaped_array=dummy_array.reshape((3,3))
print(reshaped_array)

[[2 3 4]
 [5 6 7]
 [8 9 0]]
